# Generated by Django 5.0.6 on 2024-10-01 20:44

import app.models.workspace
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_workspace_assets_exclude_name_contains"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="anthropic_api_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="openai_api_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="id",
            field=models.CharField(
                default=app.models.workspace.generate_short_uuid,
                editable=False,
                max_length=6,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
