# Generated by Django 5.0.6 on 2024-10-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_workspace_anthropic_api_key_workspace_openai_api_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="anthropic_api_key",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="openai_api_key",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
