# Generated by Django 5.0.6 on 2024-10-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_alter_workspace_anthropic_api_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="anthropic_api_key",
            field=models.BinaryField(blank=True, default=b""),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="openai_api_key",
            field=models.BinaryField(blank=True, default=b""),
        ),
    ]
