# Generated by Django 5.0.6 on 2024-10-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_alter_workspace_anthropic_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="provider_in_use",
            field=models.CharField(
                blank=True,
                choices=[("openai", "OpenAI"), ("anthropic", "Anthropic")],
                max_length=255,
                null=True,
            ),
        ),
    ]
