# Generated by Django 5.0.6 on 2024-10-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_workspace_provider_in_use"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="provider_in_use",
            field=models.CharField(
                blank=True,
                choices=[("openai", "OpenAI"), ("anthropic", "Anthropic")],
                max_length=20,
                null=True,
            ),
        ),
    ]
